//
// Created by xmmmmmovo on 2023/7/26.
//

#ifndef VOXEL_RENDERER_GRAPHICS_ADAPTERS_VK_ADAPTER_HPP
#define VOXEL_RENDERER_GRAPHICS_ADAPTERS_VK_ADAPTER_HPP

namespace voxel {}

#endif//VOXEL_RENDERER_GRAPHICS_ADAPTERS_VK_ADAPTER_HPP
