//
// Created by xmmmmmovo on 2023/7/26.
//

#ifndef VOXEL_RENDERER_GUI_ADAPTERS_IMGUI_OPENGL_ADAPTER_HPP
#define VOXEL_RENDERER_GUI_ADAPTERS_IMGUI_OPENGL_ADAPTER_HPP

class ImGuiOpenGLAdapter {};

#endif//VOXEL_RENDERER_GUI_ADAPTERS_IMGUI_OPENGL_ADAPTER_HPP
