//
// Created by xmmmmmovo on 28/07/2023.
//

#ifndef VOXEL_RENDERER_GUI_IMGUI_ADAPTERS_IMGUI_VULKAN_ADAPTER_HPP
#define VOXEL_RENDERER_GUI_IMGUI_ADAPTERS_IMGUI_VULKAN_ADAPTER_HPP

namespace voxel {}

#endif//VOXEL_RENDERER_GUI_IMGUI_ADAPTERS_IMGUI_VULKAN_ADAPTER_HPP
